learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#tempalte URLs
#this --app_name-- is used when telling the project on the project/urls.py to skip the project URLS FILES
#instead use the app/URLS.py file.
#you would use the --app_name-- lis so
# template page html --- {% url 'basic_app:user_login'%}
#you can see the --:user_login-- is also called below.
app_name = "basic_app"

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    #include allows us to use a different URLS page to find the redirect
    #you know its being used when the template link uses {% url 'basic_app:'%}
    #that link tells this page to send the 'basic_app:login' ":login" data to the app/urls.py
    #we can use the --basic_app-- name because we established in it the app/urls.py file
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^admin/', admin.site.urls),
    #name=logout is the name you use when linking to this URL redirect
    #it then looks into the apps/views.py file for user_logout function
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#how to add more attributes to the users
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    #create a password form field
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        #add fields
        fields = ('portfolio_site','profile_pic')


#when creatign a form. You must first make it here.
#then ADD it the views page (from basic_app.forms import UserLoginForm)
#then call this form simply by (user_login_form = UserLoginForm())
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileForm,UserForm,UserLoginForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return render(request,'basic_app/special.html',{})

#decorator allows us to only run this function if the user is logged in.
@login_required
def user_logout(request):
    #log the user log
    logout(request)
    #redirect them back to the home page
    return HttpResponseRedirect(reverse('index'))

def register(request):
    #has someone been registered
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            #save the user information to the database.
            user = user_form.save()
            #HASING the passowrd
            user.set_password(user.password)
            #now saved the hashed PasswordInput
            user.save()

            profile = profile_form.save(commit=False)

            profile.user = user
            #profile_pic is the form field
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profoile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        #set up the form.
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})
def user_login(request):
    user_login_form = UserLoginForm()
    #if user has pressed login
    if request.method == 'POST':
                                    #username comes from the form name='username' attribute
        username = request.POST.get('username')
        password = request.POST.get('password')
        #authenticate username
        user = authenticate(username=username,password=password)

        #if we have a username
        if user:
            #check to see if the account is active
            if user.is_active:
                #log the active user in
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active!')
        else:
            print('someone tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))
            return HttpResponse('Invalid login details supplied!')

    return render(request,'basic_app/login.html',{'user_login_form':user_login_form})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block title_block%}
    <!-- Dynamically add the titel to the pages. -->
    {% endblock %}
    <!DOCTYPE html>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      </head>
      <body>
        <nav class="navbar sticky-top navbar-dark bg-primary">
      <a class="navbar-brand" href="{% url 'index' %}">Django:MTV {% if user.is_authenticated %} | Welcome, {{user.username}}{% endif %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'special' %}">Special Page</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:register' %}">Sign Up</a>
          </li>
        </ul>
        <span class="navbar-text">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </span>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}
      <!-- anything outside of this will be inherited if you extyend! -->
      {% endblock %}
    </div>
      </body>
    </html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block title_block %}
<title>Django:MTV - Home Page</title>
{% endblock %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to Django:MTV Home Page</h1>
  <p>Please login in or Sign up to become a User.</p>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login!</h1>
  <!-- user_login comes from the app/views.oy file.  -->
  {% if user.is_authenticated %}
    {{user.username}}, you're already logged in. View the special page <a href="special/">here</a>.
  {% else %}
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    {{ user_login_form.as_p}}
    <input type="submit" value="Login">
  </form>
{% endif %}
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}

{% block title_block %}
<title>Django:MTV - Registration Page</title>
{% endblock %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thanks for registering.</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form here:</h3>
    <!-- to eb able to pass images via the form enctype="multipart/form-data" -->
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="btn btn-primary" value="Register">

    </form>
  {% endif %}
</div>
{% endblock %}

learning_users/templates/basic_app/special.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block title_block %}
<title>Django:MTV - Home Page</title>
{% endblock %}
{% block body_block %}
<div class="jumbotron">
  <h1>MTV Special Page</h1>
  <p>Only those logged in can see this page because of pythons decorators.</p>
  <p>{{ user.username }}</p>
</div>
{% endblock %}